version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9.0
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo

jobs:
  build:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: Run tests
          command: |
            pipenv run python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - run:
          name: Push To Heroku
          command: |
            git push heroku master:master
            heroku run python manage.py migrate
            sleep 5
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
