# Generated by Django 3.2 on 2021-05-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='controller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_circuit', to=settings.AUTH_USER_MODEL),
        ),
    ]
