# Generated by Django 3.2.1 on 2021-05-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarden', '0002_circuit_controller'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
