# Generated by Django 3.2.3 on 2021-05-22 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarden', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='controller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_circuit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='health_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='health check'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='user name'),
        ),
        migrations.CreateModel(
            name='CircuitCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartgarden.circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='related_circuits', through='smartgarden.CircuitCollaboration', to=settings.AUTH_USER_MODEL),
        ),
    ]
