# Generated by Django 3.2.3 on 2021-05-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarden', '0005_remove_circuit_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_log', to='smartgarden.circuit')),
            ],
        ),
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
